adjective=input("Введите прилагательное: ")
noun=input("Введите существительное: ")
verb=input("Введите глагол в прошедшем времени: ")
print("Ваша MadLib")
print ("Этот" , adjective, noun, verb, "на ленивого розавого слона.")
