adjective=input("Введите прилагательное: ")
noun=input("Введите существительное: ")
verb=input("Введите глагол в прошедшем времени: ")
animal=input("Введите название животного с предлогом 'на': ")
print("Ваша MadLib")
print ("Эта" , adjective, noun, verb, "на ленивого розавого", animal,".")
